[package]
name = "elevators"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = { version = "0.12.0", features = ["metal"] }

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
